branch-defaults:
  master:
    environment: Trainhopper-dev
global:
  application_name: Trainhopper
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Node.js
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli2
  repository: null
  sc: git
  workspace_type: Application
